services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    environment:
      DOMAIN: "https://vaultwarden.leonardonels.com"
    volumes:
      - /opt/docker/roxan/data/vaultwarden/:/data/
    ports:
      - 10000:80
